using System.Collections.ObjectModel;
using System.Formats.Tar;
using System.IO.Compression;
using System.Reflection;
using System.Security.Cryptography;
using System.Text;

namespace CsWebUi;

/// <summary>
/// An immutable, in-memory file system suitable for serving an embedded web application.
/// </summary>
/// <remarks>
/// Archive contents are decompressed eagerly. HTTP responses are created lazily and stored in
/// pinned managed memory so WebUI can safely consume them without extracting files to disk.
/// </remarks>
public sealed class WebUiVirtualFileSystem
{
    private static readonly byte[] OptimizedArchiveMagic = "CSWVFS01"u8.ToArray();
    private static readonly UTF8Encoding StrictUtf8 = new(
        encoderShouldEmitUTF8Identifier: false,
        throwOnInvalidBytes: true);

    /// <summary>The default manifest-resource name generated by CsWebUi's build target.</summary>
    public const string DefaultResourceName = "CsWebUi.StaticFiles";

    private static readonly byte[] NotFoundResponse = CreatePinnedHttpResponse(
        "text/plain; charset=utf-8",
        "no-store",
        "Not found"u8.ToArray(),
        status: "404 Not Found");

    private readonly ReadOnlyDictionary<string, FileEntry> _files;
    private readonly IReadOnlyCollection<string> _paths;
    private readonly string _indexFile;
    private readonly bool _enableSinglePageApplicationFallback;

    private WebUiVirtualFileSystem(
        Dictionary<string, FileEntry> files,
        WebUiVirtualFileSystemOptions options)
    {
        _files = new ReadOnlyDictionary<string, FileEntry>(files);
        _paths = Array.AsReadOnly(files.Keys.Order(StringComparer.Ordinal).ToArray());
        _indexFile = NormalizeConfiguredPath(options.IndexFile, nameof(options.IndexFile));
        _enableSinglePageApplicationFallback = options.EnableSinglePageApplicationFallback;
    }

    /// <summary>Gets the normalized, case-sensitive paths contained in this file system.</summary>
    public IReadOnlyCollection<string> Files => _paths;

    /// <summary>Loads all files below <paramref name="path"/> into memory.</summary>
    public static WebUiVirtualFileSystem FromDirectory(
        string path,
        WebUiVirtualFileSystemOptions? options = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        options ??= new WebUiVirtualFileSystemOptions();
        ValidateOptions(options);

        var root = Path.GetFullPath(path);
        if (!Directory.Exists(root))
        {
            throw new DirectoryNotFoundException($"The virtual file-system directory '{root}' does not exist.");
        }

        var builder = new FileSystemBuilder(options);
        var enumerationOptions = new EnumerationOptions
        {
            RecurseSubdirectories = true,
            AttributesToSkip = FileAttributes.ReparsePoint,
        };
        foreach (var file in Directory.EnumerateFiles(root, "*", enumerationOptions))
        {
            var relativePath = Path.GetRelativePath(root, file).Replace(Path.DirectorySeparatorChar, '/');
            builder.Reserve(relativePath, new FileInfo(file).Length);
            builder.AddReserved(relativePath, File.ReadAllBytes(file));
        }

        return builder.Build();
    }

    /// <summary>
    /// Loads an optimized CsWebUi, ZIP, or Brotli-compressed TAR archive from an assembly manifest resource.
    /// </summary>
    public static WebUiVirtualFileSystem FromEmbeddedArchive(
        Assembly assembly,
        string resourceName = DefaultResourceName,
        WebUiVirtualFileSystemOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(assembly);
        ArgumentException.ThrowIfNullOrWhiteSpace(resourceName);

        using var stream = assembly.GetManifestResourceStream(resourceName)
            ?? throw new ArgumentException(
                $"Assembly '{assembly.GetName().Name}' does not contain manifest resource '{resourceName}'.",
                nameof(resourceName));

        return FromArchive(stream, options);
    }

    /// <summary>
    /// Loads an optimized CsWebUi, ZIP, or Brotli-compressed TAR archive and keeps its
    /// decompressed files in memory.
    /// </summary>
    public static WebUiVirtualFileSystem FromArchive(
        Stream archive,
        WebUiVirtualFileSystemOptions? options = null)
    {
        ArgumentNullException.ThrowIfNull(archive);
        if (!archive.CanRead)
        {
            throw new ArgumentException("The archive stream must be readable.", nameof(archive));
        }

        options ??= new WebUiVirtualFileSystemOptions();
        ValidateOptions(options);

        var input = EnsureSeekable(archive);
        try
        {
            if (HasSignature(input, OptimizedArchiveMagic))
            {
                return ReadOptimizedArchive(input, options);
            }

            return HasZipSignature(input)
                ? ReadZip(input, options)
                : ReadBrotliTar(input, options);
        }
        finally
        {
            if (!ReferenceEquals(input, archive))
            {
                input.Dispose();
            }
        }
    }

    /// <summary>Gets a file by URL-style path.</summary>
    public bool TryGetFile(string path, out ReadOnlyMemory<byte> content)
    {
        if (TryResolve(path, out var entry))
        {
            content = entry.Content;
            return true;
        }

        content = default;
        return false;
    }

    /// <summary>Opens a read-only stream over a file's in-memory contents.</summary>
    public Stream OpenRead(string path)
    {
        if (!TryResolve(path, out var entry))
        {
            throw new FileNotFoundException($"The virtual file '{path}' does not exist.", path);
        }

        return new MemoryStream(
            entry.Buffer,
            entry.Offset,
            entry.Length,
            writable: false,
            publiclyVisible: false);
    }

    internal byte[] GetHttpResponse(string path)
        => TryResolve(path, out var entry) ? entry.HttpResponse.Value : NotFoundResponse;

    private static WebUiVirtualFileSystem ReadZip(Stream input, WebUiVirtualFileSystemOptions options)
    {
        var builder = new FileSystemBuilder(options);
        using var archive = new ZipArchive(input, ZipArchiveMode.Read, leaveOpen: true);
        foreach (var entry in archive.Entries)
        {
            if (string.IsNullOrEmpty(entry.Name))
            {
                continue;
            }

            builder.Reserve(entry.FullName, entry.Length);
            using var entryStream = entry.Open();
            builder.AddReserved(entry.FullName, ReadFile(entryStream, entry.Length));
        }

        return builder.Build();
    }

    private static WebUiVirtualFileSystem ReadOptimizedArchive(
        Stream input,
        WebUiVirtualFileSystemOptions options)
    {
        using var reader = new BinaryReader(input, Encoding.UTF8, leaveOpen: true);
        if (!reader.ReadBytes(OptimizedArchiveMagic.Length).AsSpan().SequenceEqual(OptimizedArchiveMagic))
        {
            throw new InvalidDataException("The optimized virtual file-system archive has an invalid signature.");
        }

        var fileCount = reader.ReadInt32();
        var groupCount = reader.ReadInt32();
        if (fileCount < 0 || fileCount > options.MaxFileCount)
        {
            throw new InvalidDataException(
                $"The archive file count is outside the configured {options.MaxFileCount} file limit.");
        }

        if (groupCount is < 0 or > 16)
        {
            throw new InvalidDataException("The archive contains an unsupported number of data groups.");
        }

        var manifest = new OptimizedEntry[fileCount];
        var normalizedPaths = new HashSet<string>(StringComparer.Ordinal);
        long totalBytes = 0;
        for (var index = 0; index < manifest.Length; index++)
        {
            var pathLength = reader.ReadInt32();
            if (pathLength is <= 0 or > 1024 * 1024)
            {
                throw new InvalidDataException("The archive contains an invalid path length.");
            }

            var pathBytes = ReadExactly(reader, pathLength);
            string path;
            try
            {
                path = NormalizeConfiguredPath(StrictUtf8.GetString(pathBytes), "path");
            }
            catch (DecoderFallbackException exception)
            {
                throw new InvalidDataException("The archive contains a non-UTF-8 virtual path.", exception);
            }
            catch (ArgumentException exception)
            {
                throw new InvalidDataException("The archive contains an invalid virtual path.", exception);
            }

            if (!normalizedPaths.Add(path))
            {
                throw new InvalidDataException($"The archive contains duplicate path '{path}'.");
            }

            var group = reader.ReadInt32();
            var offset = reader.ReadInt64();
            var length = reader.ReadInt64();
            var hash = ReadExactly(reader, SHA256.HashSizeInBytes);
            if (group < 0 || group >= groupCount || offset < 0 || length < 0 || length > int.MaxValue)
            {
                throw new InvalidDataException($"Virtual file '{path}' has invalid group metadata.");
            }

            if (length > options.MaxTotalUncompressedBytes - totalBytes)
            {
                throw new InvalidDataException(
                    $"The archive exceeds the {options.MaxTotalUncompressedBytes} byte uncompressed-size limit.");
            }

            totalBytes += length;
            manifest[index] = new OptimizedEntry(
                path,
                group,
                offset,
                checked((int)length),
                hash);
        }

        var groups = new byte[groupCount][];
        long totalGroupBytes = 0;
        for (var index = 0; index < groups.Length; index++)
        {
            var compression = reader.ReadByte();
            var uncompressedLength = reader.ReadInt64();
            var payloadLength = reader.ReadInt64();
            if (uncompressedLength < 0
                || uncompressedLength > int.MaxValue
                || uncompressedLength > options.MaxTotalUncompressedBytes
                || payloadLength < 0
                || payloadLength > int.MaxValue
                || payloadLength > options.MaxTotalUncompressedBytes
                || uncompressedLength > options.MaxTotalUncompressedBytes - totalGroupBytes)
            {
                throw new InvalidDataException("The archive contains an invalid data-group size.");
            }

            totalGroupBytes += uncompressedLength;
            var payload = ReadExactly(reader, checked((int)payloadLength));
            groups[index] = compression switch
            {
                0 when payloadLength == uncompressedLength => payload,
                1 => DecompressBrotli(payload, checked((int)uncompressedLength)),
                0 => throw new InvalidDataException("A stored group has mismatched sizes."),
                _ => throw new InvalidDataException($"Unsupported data-group compression method {compression}."),
            };
        }

        if (input.Position != input.Length)
        {
            throw new InvalidDataException("The archive contains trailing data.");
        }

        if (totalGroupBytes != totalBytes)
        {
            throw new InvalidDataException(
                "The archive manifest and data groups have mismatched uncompressed sizes.");
        }

        var builder = new FileSystemBuilder(options);
        foreach (var entry in manifest)
        {
            var group = groups[entry.Group];
            if (entry.Offset > group.LongLength - entry.Length)
            {
                throw new InvalidDataException(
                    $"Virtual file '{entry.Path}' points outside its data group.");
            }

            var offset = checked((int)entry.Offset);
            var content = group.AsSpan(offset, entry.Length);
            var actualHash = SHA256.HashData(content);
            if (!CryptographicOperations.FixedTimeEquals(actualHash, entry.Hash))
            {
                throw new InvalidDataException(
                    $"Virtual file '{entry.Path}' failed its integrity check.");
            }

            builder.AddShared(entry.Path, group, offset, entry.Length);
        }

        return builder.Build();
    }

    private static WebUiVirtualFileSystem ReadBrotliTar(Stream input, WebUiVirtualFileSystemOptions options)
    {
        var builder = new FileSystemBuilder(options);
        using var brotli = new BrotliStream(input, CompressionMode.Decompress, leaveOpen: true);
        using var tar = new TarReader(brotli, leaveOpen: true);

        while (tar.GetNextEntry(copyData: false) is { } entry)
        {
            if (entry.EntryType is not (TarEntryType.RegularFile or TarEntryType.V7RegularFile))
            {
                continue;
            }

            builder.Reserve(entry.Name, entry.Length);
            builder.AddReserved(
                entry.Name,
                ReadFile(
                    entry.DataStream ?? throw new InvalidDataException($"TAR entry '{entry.Name}' has no data."),
                    entry.Length));
        }

        return builder.Build();
    }

    private static MemoryStream EnsureSeekable(Stream archive)
    {
        if (archive.CanSeek)
        {
            archive.Position = 0;
            return archive as MemoryStream ?? CopyToMemory(archive);
        }

        return CopyToMemory(archive);
    }

    private static MemoryStream CopyToMemory(Stream source)
    {
        var copy = new MemoryStream();
        source.CopyTo(copy);
        copy.Position = 0;
        return copy;
    }

    private static bool HasZipSignature(Stream stream)
    {
        Span<byte> signature = stackalloc byte[4];
        var read = stream.Read(signature);
        stream.Position = 0;
        return read == signature.Length
            && signature[0] == (byte)'P'
            && signature[1] == (byte)'K'
            && signature[2] is 3 or 5 or 7
            && signature[3] is 4 or 6 or 8;
    }

    private static bool HasSignature(Stream stream, ReadOnlySpan<byte> expected)
    {
        var signature = new byte[expected.Length];
        var read = stream.Read(signature);
        stream.Position = 0;
        return read == signature.Length && signature.AsSpan().SequenceEqual(expected);
    }

    private static byte[] ReadExactly(BinaryReader reader, int length)
    {
        var result = reader.ReadBytes(length);
        return result.Length == length
            ? result
            : throw new InvalidDataException("The archive ended unexpectedly.");
    }

    private static byte[] DecompressBrotli(byte[] payload, int uncompressedLength)
    {
        var output = GC.AllocateUninitializedArray<byte>(uncompressedLength);
        using var input = new MemoryStream(payload, writable: false);
        using var brotli = new BrotliStream(input, CompressionMode.Decompress);
        brotli.ReadExactly(output);
        if (brotli.ReadByte() != -1)
        {
            throw new InvalidDataException("A Brotli group contains more data than declared.");
        }

        return output;
    }

    private static byte[] ReadFile(Stream stream, long declaredLength)
    {
        if (declaredLength > int.MaxValue)
        {
            throw new InvalidDataException("A virtual file cannot be larger than 2 GiB.");
        }

        using var output = new MemoryStream(checked((int)declaredLength));
        stream.CopyTo(output);
        if (output.Length != declaredLength)
        {
            throw new InvalidDataException(
                $"Archive entry declared {declaredLength} bytes but contained {output.Length} bytes.");
        }

        return output.ToArray();
    }

    private bool TryResolve(string path, out FileEntry entry)
    {
        if (!TryNormalizeRequestPath(path, out var normalized))
        {
            entry = null!;
            return false;
        }

        if (_files.TryGetValue(normalized, out entry!))
        {
            return true;
        }

        var indexPath = normalized.Length == 0
            ? _indexFile
            : normalized.EndsWith('/')
                ? normalized + _indexFile
                : normalized + "/" + _indexFile;

        if (_files.TryGetValue(indexPath, out entry!))
        {
            return true;
        }

        if (_enableSinglePageApplicationFallback
            && !normalized.EndsWith('/')
            && !HasFileExtension(normalized)
            && _files.TryGetValue(_indexFile, out entry!))
        {
            return true;
        }

        entry = null!;
        return false;
    }

    private static bool TryNormalizeRequestPath(string path, out string normalized)
    {
        normalized = string.Empty;
        if (string.IsNullOrEmpty(path) || path == "/")
        {
            return true;
        }

        try
        {
            var queryIndex = path.IndexOfAny(['?', '#']);
            var pathOnly = queryIndex < 0 ? path : path[..queryIndex];
            pathOnly = Uri.UnescapeDataString(pathOnly);
            if (pathOnly.Contains('\0') || pathOnly.Contains('\\'))
            {
                return false;
            }

            var segments = pathOnly.Split('/', StringSplitOptions.RemoveEmptyEntries);
            var resolved = new List<string>(segments.Length);
            foreach (var segment in segments)
            {
                if (segment == ".")
                {
                    continue;
                }

                if (segment == "..")
                {
                    return false;
                }

                resolved.Add(segment);
            }

            normalized = string.Join('/', resolved);
            if (pathOnly.EndsWith('/') && normalized.Length > 0)
            {
                normalized += "/";
            }

            return true;
        }
        catch (UriFormatException)
        {
            return false;
        }
    }

    private static string NormalizeConfiguredPath(string path, string parameterName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(path, parameterName);
        if (!TryNormalizeRequestPath(path, out var normalized)
            || normalized.Length == 0
            || normalized.EndsWith('/'))
        {
            throw new ArgumentException("The path must identify a file below the virtual root.", parameterName);
        }

        return normalized;
    }

    private static bool HasFileExtension(string path)
    {
        var name = path[(path.LastIndexOf('/') + 1)..];
        var dot = name.LastIndexOf('.');
        return dot > 0 && dot < name.Length - 1;
    }

    private static void ValidateOptions(WebUiVirtualFileSystemOptions options)
    {
        ArgumentOutOfRangeException.ThrowIfLessThan(options.MaxFileCount, 1);
        ArgumentOutOfRangeException.ThrowIfLessThan(options.MaxTotalUncompressedBytes, 1);
        _ = NormalizeConfiguredPath(options.IndexFile, nameof(options.IndexFile));
    }

    private static byte[] CreatePinnedHttpResponse(
        string contentType,
        string cacheControl,
        ReadOnlyMemory<byte> content,
        string status = "200 OK")
    {
        var header = Encoding.ASCII.GetBytes(
            $"HTTP/1.1 {status}\r\n" +
            $"Content-Type: {contentType}\r\n" +
            $"Content-Length: {content.Length}\r\n" +
            $"Cache-Control: {cacheControl}\r\n" +
            "X-Content-Type-Options: nosniff\r\n" +
            "\r\n");
        var response = GC.AllocateUninitializedArray<byte>(
            checked(header.Length + content.Length),
            pinned: true);
        header.CopyTo(response, 0);
        content.Span.CopyTo(response.AsSpan(header.Length));
        return response;
    }

    private static string GetContentType(string path)
        => Path.GetExtension(path).ToLowerInvariant() switch
        {
            ".html" or ".htm" => "text/html; charset=utf-8",
            ".css" => "text/css; charset=utf-8",
            ".js" or ".mjs" => "text/javascript; charset=utf-8",
            ".json" or ".map" => "application/json; charset=utf-8",
            ".txt" => "text/plain; charset=utf-8",
            ".xml" => "application/xml; charset=utf-8",
            ".svg" => "image/svg+xml",
            ".png" => "image/png",
            ".jpg" or ".jpeg" => "image/jpeg",
            ".gif" => "image/gif",
            ".webp" => "image/webp",
            ".avif" => "image/avif",
            ".ico" => "image/x-icon",
            ".wasm" => "application/wasm",
            ".woff" => "font/woff",
            ".woff2" => "font/woff2",
            ".ttf" => "font/ttf",
            ".otf" => "font/otf",
            ".webmanifest" => "application/manifest+json",
            ".pdf" => "application/pdf",
            ".mp4" => "video/mp4",
            ".webm" => "video/webm",
            ".mp3" => "audio/mpeg",
            ".wav" => "audio/wav",
            _ => "application/octet-stream",
        };

    private sealed class FileEntry
    {
        internal FileEntry(string path, byte[] buffer, int offset, int length)
        {
            Buffer = buffer;
            Offset = offset;
            Length = length;
            HttpResponse = new Lazy<byte[]>(
                () => CreatePinnedHttpResponse(
                    GetContentType(path),
                    path.EndsWith(".html", StringComparison.OrdinalIgnoreCase)
                        ? "no-cache"
                        : "public, max-age=31536000, immutable",
                    Content),
                LazyThreadSafetyMode.ExecutionAndPublication);
        }

        internal byte[] Buffer { get; }

        internal int Offset { get; }

        internal int Length { get; }

        internal ReadOnlyMemory<byte> Content => new(Buffer, Offset, Length);

        internal Lazy<byte[]> HttpResponse { get; }
    }

    private sealed class FileSystemBuilder
    {
        private readonly Dictionary<string, FileEntry> _files = new(StringComparer.Ordinal);
        private readonly WebUiVirtualFileSystemOptions _options;
        private long _totalBytes;
        private string? _reservedPath;
        private long _reservedLength;

        internal FileSystemBuilder(WebUiVirtualFileSystemOptions options)
        {
            _options = options;
        }

        internal void Add(string path, byte[] content)
        {
            Reserve(path, content.LongLength);
            AddReserved(path, content);
        }

        internal void Reserve(string path, long length)
        {
            if (_reservedPath is not null)
            {
                throw new InvalidOperationException("The previous virtual file was not added.");
            }

            var normalized = NormalizeConfiguredPath(path, nameof(path));
            if (_files.ContainsKey(normalized))
            {
                throw new InvalidDataException($"The archive contains duplicate path '{normalized}'.");
            }

            if (_files.Count >= _options.MaxFileCount)
            {
                throw new InvalidDataException(
                    $"The archive exceeds the {_options.MaxFileCount} file limit.");
            }

            if (length < 0 || length > int.MaxValue)
            {
                throw new InvalidDataException($"Virtual file '{normalized}' has an unsupported size.");
            }

            if (length > _options.MaxTotalUncompressedBytes - _totalBytes)
            {
                throw new InvalidDataException(
                    $"The archive exceeds the {_options.MaxTotalUncompressedBytes} byte uncompressed-size limit.");
            }

            _reservedPath = normalized;
            _reservedLength = length;
        }

        internal void AddReserved(string path, byte[] content)
        {
            var normalized = NormalizeConfiguredPath(path, nameof(path));
            if (!string.Equals(normalized, _reservedPath, StringComparison.Ordinal)
                || content.LongLength != _reservedLength)
            {
                throw new InvalidDataException($"Virtual file '{normalized}' did not match its archive metadata.");
            }

            _files.Add(normalized, new FileEntry(normalized, content, 0, content.Length));
            _totalBytes += content.LongLength;
            _reservedPath = null;
            _reservedLength = 0;
        }

        internal void AddShared(string path, byte[] buffer, int offset, int length)
        {
            Reserve(path, length);
            var normalized = _reservedPath!;
            if (offset < 0 || length < 0 || offset > buffer.Length - length)
            {
                throw new InvalidDataException($"Virtual file '{normalized}' points outside its data group.");
            }

            _files.Add(normalized, new FileEntry(normalized, buffer, offset, length));
            _totalBytes += length;
            _reservedPath = null;
            _reservedLength = 0;
        }

        internal WebUiVirtualFileSystem Build()
        {
            if (_reservedPath is not null)
            {
                throw new InvalidOperationException("The final virtual file was not added.");
            }

            return new WebUiVirtualFileSystem(_files, _options);
        }
    }

    private sealed record OptimizedEntry(
        string Path,
        int Group,
        long Offset,
        int Length,
        byte[] Hash);
}
